#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
cd "$PROJECT_DIR"

echo "=== AI Runtime Monitor — Control Plane Setup ==="
echo ""

# Check prerequisites
echo "[1/6] Checking prerequisites..."
command -v docker >/dev/null 2>&1 || { echo "ERROR: docker not found. Install Docker Desktop."; exit 1; }
command -v docker compose >/dev/null 2>&1 || { echo "ERROR: docker compose not found. Update Docker Desktop."; exit 1; }
docker info >/dev/null 2>&1 || { echo "ERROR: Docker daemon not running. Start Docker Desktop."; exit 1; }

# Discover free ports
echo "[2/6] Discovering available ports..."

find_free_port() {
    local preferred=$1
    local fallbacks="${2:-}"
    if ! lsof -i :"$preferred" -sTCP:LISTEN >/dev/null 2>&1; then
        echo "$preferred"
        return
    fi
    for port in $fallbacks; do
        if ! lsof -i :"$port" -sTCP:LISTEN >/dev/null 2>&1; then
            echo "$port"
            return
        fi
    done
    echo "ERROR: No free port found (tried $preferred $fallbacks)" >&2
    exit 1
}

PG_PORT=$(find_free_port 5433 "5434 5435 5436")
CP_PORT=$(find_free_port 9090 "9091 9092 9093")

echo "  Postgres port: $PG_PORT"
echo "  Control Plane port: $CP_PORT"

# Generate secrets
echo "[3/6] Generating secrets..."
DB_PASSWORD=$(openssl rand -hex 16)
API_KEY=$(openssl rand -hex 24)

# Create .env
echo "[4/6] Creating .env..."
cat > .env <<EOF
# Auto-generated by setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# DO NOT COMMIT THIS FILE

CP_DB_HOST=postgres
CP_DB_PORT=5432
CP_DB_NAME=fleet_monitor
CP_DB_USER=monitor
CP_DB_PASSWORD=$DB_PASSWORD

CP_PORT=$CP_PORT
CP_API_KEY=$API_KEY

POSTGRES_HOST_PORT=$PG_PORT
CP_HOST_PORT=$CP_PORT
EOF

echo "  .env created with random credentials"

# Build and start
echo "[5/6] Building and starting services..."
docker compose build --quiet
docker compose up -d

# Wait for health
echo "[6/6] Waiting for services to be healthy..."
MAX_WAIT=30
WAITED=0
until docker compose exec -T postgres pg_isready -U monitor -q 2>/dev/null; do
    sleep 1
    WAITED=$((WAITED + 1))
    if [ $WAITED -ge $MAX_WAIT ]; then
        echo "ERROR: Postgres did not become ready in ${MAX_WAIT}s"
        docker compose logs postgres
        exit 1
    fi
done

# Run migrations
echo "  Running database migrations..."
docker compose exec -T control-plane python -c "from cp.db import run_migrations; run_migrations()"

echo ""
echo "=== Setup Complete ==="
echo ""
echo "  Fleet Dashboard:  http://localhost:$CP_PORT/dashboard"
echo "  Ingest API:       http://localhost:$CP_PORT/api/v1/ingest"
echo "  Endpoints API:    http://localhost:$CP_PORT/api/v1/endpoints"
echo "  Postgres:         localhost:$PG_PORT (user: monitor)"
echo ""
echo "  API Key: $API_KEY"
echo "  (saved in .env — use this to configure ai-monitor clients)"
echo ""
echo "  Connect your laptop:"
echo "    ai-monitor --start --control-plane http://localhost:$CP_PORT --cp-api-key $API_KEY"
echo ""
echo "  Test client is already running and sending fake data every 30s."
echo "  Check: curl -s http://localhost:$CP_PORT/api/v1/endpoints | python3 -m json.tool"
echo ""
